name: billing_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  http:



  print_bluetooth_thermal:
  cupertino_icons:
  table_calendar:
  google_fonts:
  flutter_datetime_picker:
  file_picker:
  shared_preferences:
  firebase_messaging:
  image_picker:
  fluttertoast: ^9.0.0
  get:
  path_provider:
  url_launcher:
  flutter_downloader:
  permission_handler:
  clipboard:
  flutter_launcher_icons:
  flutter_keyboard_visibility:
  flutter_file_downloader:
  page_transition:
  email_validator:
  dio:
  smooth_page_indicator:
#  blue_thermal_printer:
#  bluetooth_thermal_printer:
  multicast_dns:
  intl:
  device_preview:
  dotted_line: ^3.2.2
  flutter_bluetooth_printer:
  flutter_isolate:
  hexcolor:
  provider:
  flutter_thermal_printer:
  pos_universal_printer:

  http_parser: any
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/billing-logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0


flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
  